# Generated by Django 5.2.11 on 2026-02-17 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_alter_article_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(max_length=255, unique=True)),
                ('task_type', models.CharField(choices=[('train', 'Training'), ('infer', 'Inference')], max_length=10)),
                ('status', models.CharField(max_length=20)),
                ('result', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
